id: ICBA7D8C4
legacy_id: P004203
ocr_import_info:
  bdrc_scan_id: W20019
  source: bdrc
  ocr_info:
    timestamp: '2020-03-23T08:49:46'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-01T13:10:12.280265+00:00'
last_modified: 2022-09-01 21:10:20.000653
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W20019
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW20019
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དབུ་མའི་དཔྱད་པ་གཟུར་གནས་དགྱེས་པའི་གཏམ།
  author: མཁན་སྤྲུལ་བློ་བཟང་ནོར་བུ།
statistics:
  ocr_word_mean_confidence_index: 0.947557324795867
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1KG10306:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG10306
      total_pages: 166
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG10306.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.947557324795867
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
