id: ICBA7D8C4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T08:50:48+00:00'
last_modified: '2022-06-07T21:02:33.964883+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W20019
  title: དབུ་མའི་དཔྱད་པ་གཟུར་གནས་དགྱེས་པའི་གཏམ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    95FE:
      image_group_id: I1KG10306
      title: ''
      total_pages: 166
      order: 1
      base_file: 95FE.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
