id: P004203
initial_creation_type: ocr
source_metadata:
  id: bdr:W20019
  title: དབུ་མའི་དཔྱད་པ་གཟུར་གནས་དགྱེས་པའི་གཏམ།
  author: ''
  volumes:
    b3cb6c88419148af8784b92cea36f690:
      image_group_id: I1KG10306
      title: ''
      volume_number: 1
      total_pages: 166
