id: P004203
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 11:00:45.868110
source_metadata:
  id: bdr:W20019
  title: དབུ་མའི་དཔྱད་པ་གཟུར་གནས་དགྱེས་པའི་གཏམ།
  author: ''
  volumes:
    b3cb6c88419148af8784b92cea36f690:
      image_group_id: I1KG10306
      title: ''
      volume_number: 1
      total_pages: 166
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
